//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.26 at 08:14:51 PM IST 
//


package outputJavaClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Employee" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="EmployeeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="DepartmentID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "employee"
})
@XmlRootElement(name = "Employees")
public class Employees {

    @XmlElement(name = "Employee")
    protected List<Employees.Employee> employee;

    /**
     * Gets the value of the employee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmployee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Employees.Employee }
     * 
     * 
     */
    public List<Employees.Employee> getEmployee() {
        if (employee == null) {
            employee = new ArrayList<Employees.Employee>();
        }
        return this.employee;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="EmployeeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="DepartmentID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employeeID",
        "employeeName",
        "addressLine1",
        "addressLine2",
        "city",
        "zipCode",
        "email",
        "phone",
        "departmentID",
        "productID"
    })
    public static class Employee {

        @XmlElement(name = "EmployeeID")
        protected byte employeeID;
        @XmlElement(name = "EmployeeName", required = true)
        protected String employeeName;
        @XmlElement(name = "AddressLine1", required = true)
        protected String addressLine1;
        @XmlElement(name = "AddressLine2", required = true)
        protected String addressLine2;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "ZipCode")
        protected int zipCode;
        @XmlElement(name = "Email", required = true)
        protected String email;
        @XmlElement(name = "Phone")
        protected long phone;
        @XmlElement(name = "DepartmentID")
        protected byte departmentID;
        @XmlElement(name = "ProductID")
        protected byte productID;

        /**
         * Gets the value of the employeeID property.
         * 
         */
        public byte getEmployeeID() {
            return employeeID;
        }

        /**
         * Sets the value of the employeeID property.
         * 
         */
        public void setEmployeeID(byte value) {
            this.employeeID = value;
        }

        /**
         * Gets the value of the employeeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmployeeName() {
            return employeeName;
        }

        /**
         * Sets the value of the employeeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmployeeName(String value) {
            this.employeeName = value;
        }

        /**
         * Gets the value of the addressLine1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine1() {
            return addressLine1;
        }

        /**
         * Sets the value of the addressLine1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine1(String value) {
            this.addressLine1 = value;
        }

        /**
         * Gets the value of the addressLine2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine2() {
            return addressLine2;
        }

        /**
         * Sets the value of the addressLine2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine2(String value) {
            this.addressLine2 = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the zipCode property.
         * 
         */
        public int getZipCode() {
            return zipCode;
        }

        /**
         * Sets the value of the zipCode property.
         * 
         */
        public void setZipCode(int value) {
            this.zipCode = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the phone property.
         * 
         */
        public long getPhone() {
            return phone;
        }

        /**
         * Sets the value of the phone property.
         * 
         */
        public void setPhone(long value) {
            this.phone = value;
        }

        /**
         * Gets the value of the departmentID property.
         * 
         */
        public byte getDepartmentID() {
            return departmentID;
        }

        /**
         * Sets the value of the departmentID property.
         * 
         */
        public void setDepartmentID(byte value) {
            this.departmentID = value;
        }

        /**
         * Gets the value of the productID property.
         * 
         */
        public byte getProductID() {
            return productID;
        }

        /**
         * Sets the value of the productID property.
         * 
         */
        public void setProductID(byte value) {
            this.productID = value;
        }

    }

}
